[package]
name = "gravlume-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
gpu-benchmarks = ["dep:criterion"]

[dependencies]
bytemuck.workspace = true
criterion = { workspace = true, optional = true }
egui.workspace = true
egui-wgpu.workspace = true
gravlume-domain.workspace = true
gravlume-native-display.workspace = true
num-traits.workspace = true
pollster.workspace = true
thiserror.workspace = true
tracing.workspace = true
wgpu.workspace = true
winit.workspace = true

[dev-dependencies]
gravlume-reference.workspace = true
proptest.workspace = true

[[bench]]
name = "trace_gpu"
harness = false
required-features = ["gpu-benchmarks"]

[target.'cfg(target_os = "macos")'.dependencies]
wgpu = { workspace = true, features = ["metal"] }

[target.'cfg(any(target_os = "windows", target_os = "linux"))'.dependencies]
wgpu = { workspace = true, features = ["vulkan"] }

[lints]
workspace = true
